CREATE TABLE public.over_volume (
    fdate timestamp without time zone,
    machinename text,
    cmodel text,
    barcode text,
    cycletime double precision,
    printspeed_plan double precision,
    printspeed double precision,
    diff_printspeed double precision,
    abs_printspeed double precision,
    frontsqgpress_plan double precision,
    frontsqgpress double precision,
    diff_frontsqgpress double precision,
    abs_frontsqgpress double precision,
    rearsqgpress_plan double precision,
    rearsqgpress double precision,
    diff_rearsqgpress double precision,
    abs_rearsqgpress double precision,
    printmode_plan text,
    printmode text,
    printgap_plan double precision,
    printgap double precision,
    diff_printgap double precision,
    abs_printgap double precision,
    snapoffdistance_plan double precision,
    snapoffdistance double precision,
    diff_snapoffdistance double precision,
    abs_snapoffdistance double precision,
    snapoffspeed_plan double precision,
    snapoffspeed double precision,
    diff_snapoffspeed double precision,
    abs_snapoffspeed double precision,
    snapoffdelay_plan double precision,
    snapoffdelay double precision,
    diff_snapoffdelay double precision,
    abs_snapoffdelay double precision,
    cleaningafterlastboard double precision,
    sqgupspeed_plan double precision,
    sqgupspeed double precision,
    diff_sqgupspeed double precision,
    abs_sqgupspeed double precision,
    sqgdownspeed_plan double precision,
    sqgdownspeed double precision,
    diff_sqgdownspeed double precision,
    abs_sqgdownspeed double precision,
    cleaningfrequency_plan double precision,
    cleaningfrequency double precision,
    diff_cleaningfrequency double precision,
    abs_cleaningfrequency double precision,
    cleaningspeed_plan double precision,
    cleaningspeed double precision,
    diff_cleaningspeed double precision,
    abs_cleaningspeed double precision,
    printdirection text,
    pcbsize text,
    tableupx_plan double precision,
    tableupx double precision,
    diff_tableupx double precision,
    abs_tableupx double precision,
    tableupy1_plan double precision,
    tableupy1 double precision,
    diff_tableupy1 double precision,
    abs_tableupy1 double precision,
    tableupy2_plan double precision,
    tableupy2 double precision,
    diff_tableupy2 double precision,
    abs_tableupy2 double precision,
    xforward_plan double precision,
    xforward double precision,
    diff_xforward double precision,
    abs_xforward double precision,
    y1forward_plan double precision,
    y1forward double precision,
    diff_y1forward double precision,
    abs_y1forward double precision,
    y2forward_plan double precision,
    y2forward double precision,
    diff_y2forward double precision,
    abs_y2forward double precision,
    xbackward_plan double precision,
    xbackward double precision,
    diff_xbackward double precision,
    abs_xbackward double precision,
    y1backward_plan double precision,
    y1backward double precision,
    diff_y1backward double precision,
    abs_y1backward double precision,
    y2backward_plan double precision,
    y2backward double precision,
    diff_y2backward double precision,
    abs_y2backward double precision,
    markdeviation_plan double precision,
    markdeviation double precision,
    diff_markdeviation double precision,
    abs_markdeviation double precision,
    table_to_printing_pos_plan double precision,
    table_to_printing_pos double precision,
    diff_table_to_printing_pos double precision,
    abs_table_to_printing_pos double precision,
    table_to_snapoff_pos_plan double precision,
    table_to_snapoff_pos double precision,
    diff_table_to_snapoff_pos double precision,
    abs_table_to_snapoff_pos double precision,
    temperature double precision,
    humidity double precision,
    compname text,
    comp_errname text,
    comp_avdp double precision,
    comp_aadp double precision,
    comp_ahdp double precision,
    comp_px double precision,
    comp_py double precision
);



